"""adding petTreatment

Revision ID: faf458d599ff
Revises: bb756977011d
Create Date: 2025-06-27 10:32:15.609293

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'faf458d599ff'
down_revision = 'bb756977011d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('pet_treatments',
    sa.Column('pet_id', sa.Integer(), nullable=False),
    sa.Column('treatment_id', sa.Integer(), nullable=False),
    sa.Column('treatment_date', sa.DateTime(), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['pet_id'], ['pets.id'], name=op.f('fk_pet_treatments_pet_id_pets')),
    sa.ForeignKeyConstraint(['treatment_id'], ['treatments.id'], name=op.f('fk_pet_treatments_treatment_id_treatments')),
    sa.PrimaryKeyConstraint('pet_id', 'treatment_id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('pet_treatments')
    # ### end Alembic commands ###
